executor: CeleryExecutor
defaultAirflowRepository: airflow
defaultAirflowTag: latest

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-claim

logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-claim

workers.replicas: 0
redis.enabled: false

securityContext:
  fsGroup: 0
  runAsGroup: 0
  runAsUser: 0

config:
  webserver:
    expose_config: 'True'
  core:
    parallelism: 16